gse:
    pattern:  /
    defaults: { _controller: "gseBlogBundle:PostGSE:index" }

gse_listar:
    pattern:  /listar
    defaults: { _controller: "gseBlogBundle:PostGSE:listar" }


gse_new:
    pattern:  /new
    defaults: { _controller: "gseBlogBundle:PostGSE:new" }

gse_create:
    pattern:  /create
    defaults: { _controller: "gseBlogBundle:PostGSE:create" }

gse_new:
    pattern:  /new
    defaults: { _controller: "gseBlogBundle:PostGSE:new" }