<?php

namespace gse\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findWithfilter($data=null)
    {
        $titulo = isset($data['titulo']) ? "p.titulo  like '%".$data['titulo']."%' and ": "";
        $cuerpo = isset($data['cuerpo']) ? "p.cuerpo  like '%".$data['cuerpo']."%' and": "";
        if (isset($data['tag']) && count($data['tag']) > 0)
        {
            $tags = "t.id in (";
            $tag_id = array();
            foreach($data['tag'] as $tag)
            {
                $tag_id[] = $tag->getId();
            }
            $tags.=join(",",$tag_id).")";
        }
        else
        {
            $tags = "p.id=p.id";
            $tags = "p.id=p.id";
        }
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            "select
                p
            from
                gseBlogBundle:Post as p
                join p.tags t
            where
               $titulo
               $cuerpo
               $tags
                "
        )->getResult();

        return $query;
    }
}
